steps:
  # Step 1: Install dependencies
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install
        chmod +x ./node_modules/.bin/react-scripts || true
    dir: 'frontend'

  # Step 2: Build React project
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm run build
    dir: 'frontend'

  # Step 3: Deploy to App Engine
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - app
      - deploy
      - app.yaml
      - '--quiet'
    dir: 'frontend'

options:
  logging: CLOUD_LOGGING_ONLY
